[tool.poetry]
name = "labzen"
version = "0.1.0"
description = "A Python package to help the MDS Students to manage their labs in iPython notebooks"
authors = ["Sukhdeep kaur <sukhdeep_2929@yahoo.com>", "Rafael Pilliard Hellwig", "Kamal Moravej Jahromi"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.2.3"
nbformat = "^5.1.2"
PyGithub = "^1.54.1"
GitPython = "^3.1.14"
glob2 = "^0.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
flake8 = "^3.8.4"
pytest-cov = "^2.11.1"
codecov = "^2.1.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
